#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : opencv
Version  : 4.5.2
Release  : 303
URL      : file:///aot/build/clearlinux/packages/opencv/opencv-v4.5.2.tar.gz
Source0  : file:///aot/build/clearlinux/packages/opencv/opencv-v4.5.2.tar.gz
Source1  : file:///aot/build/clearlinux/packages/opencv/opencv_contrib-v4.5.2.tar.gz
Summary  : Open Source Computer Vision Library
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 MIT
Requires: opencv-bin = %{version}-%{release}
Requires: opencv-data = %{version}-%{release}
Requires: opencv-python = %{version}-%{release}
Requires: opencv-python3 = %{version}-%{release}
Requires: numpy
Requires: onnx
Requires: tensorflow
BuildRequires : Cython
BuildRequires : Cython-python
BuildRequires : ImageMagick-dev
BuildRequires : LuaJIT-dev
BuildRequires : LuaJIT-staticdev
BuildRequires : PyYAML
BuildRequires : Pygments
BuildRequires : SDL2
BuildRequires : SDL2-dev
BuildRequires : SDL2-staticdev
BuildRequires : SVT-AV1-dev
BuildRequires : SVT-AV1-staticdev
BuildRequires : SVT-HEVC-dev
BuildRequires : SVT-HEVC-staticdev
BuildRequires : Sphinx
BuildRequires : VTK-dev
BuildRequires : Vulkan-Headers
BuildRequires : Vulkan-Headers-dev
BuildRequires : Vulkan-Loader
BuildRequires : Vulkan-Loader-dev
BuildRequires : Vulkan-Tools
BuildRequires : Vulkan-ValidationLayers
BuildRequires : Z3-dev
BuildRequires : Z3-staticdev
BuildRequires : acl
BuildRequires : acl-dev
BuildRequires : acl-staticdev
BuildRequires : ade-data
BuildRequires : ade-dev
BuildRequires : alsa-firmware
BuildRequires : alsa-lib-dev
BuildRequires : alsa-lib-lib
BuildRequires : alsa-plugins
BuildRequires : alsa-plugins-lib
BuildRequires : alsa-tools
BuildRequires : alsa-ucm-conf
BuildRequires : alsa-utils
BuildRequires : apache-ant
BuildRequires : asciidoctor-dev
BuildRequires : beautifulsoup4
BuildRequires : binutils
BuildRequires : binutils-dev
BuildRequires : binutils-staticdev
BuildRequires : brotli
BuildRequires : brotli-dev
BuildRequires : brotli-staticdev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-qmake
BuildRequires : bzip2
BuildRequires : bzip2-dev
BuildRequires : bzip2-staticdev
BuildRequires : ca-certs
BuildRequires : ca-certs-static
BuildRequires : cairo
BuildRequires : cairo-dev
BuildRequires : cairo-lib
BuildRequires : clazy
BuildRequires : cmake
BuildRequires : compat-gcc-10
BuildRequires : compat-gcc-10-dev
BuildRequires : cppcheck
BuildRequires : curl-dev
BuildRequires : dav1d-dev
BuildRequires : dav1d-staticdev
BuildRequires : dbus
BuildRequires : dbus-broker
BuildRequires : dbus-dev
BuildRequires : dbus-glib
BuildRequires : dbus-glib-dev
BuildRequires : dbus-python
BuildRequires : doxygen
BuildRequires : e2fsprogs-dev
BuildRequires : eigen
BuildRequires : eigen-data
BuildRequires : eigen-dev
BuildRequires : elfutils-dev
BuildRequires : evtest
BuildRequires : expat-dev
BuildRequires : expat-dev32
BuildRequires : expat-staticdev
BuildRequires : extra-cmake-modules pkgconfig(OpenEXR)
BuildRequires : fftw-dev
BuildRequires : fftw-staticdev
BuildRequires : findutils
BuildRequires : flac-dev
BuildRequires : flac-staticdev
BuildRequires : fontconfig-data
BuildRequires : fontconfig-dev
BuildRequires : fontconfig-lib
BuildRequires : fontconfig-staticdev
BuildRequires : freetype-dev
BuildRequires : freetype-lib
BuildRequires : freetype-staticdev
BuildRequires : fribidi-dev
BuildRequires : fribidi-staticdev
BuildRequires : gcc
BuildRequires : gcc-dev
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libs-math
BuildRequires : gcc-libstdc++32
BuildRequires : gcc-libubsan
BuildRequires : gcc-locale
BuildRequires : gdal
BuildRequires : gdal-dev
BuildRequires : gdal-staticdev
BuildRequires : gdb
BuildRequires : gdb-dev
BuildRequires : gettext
BuildRequires : gflags-dev
BuildRequires : glib
BuildRequires : glib-bin
BuildRequires : glib-data
BuildRequires : glib-dev
BuildRequires : glib-dev32
BuildRequires : glib-lib
BuildRequires : glib-staticdev
BuildRequires : glibc
BuildRequires : glibc-dev
BuildRequires : glibc-dev32
BuildRequires : glibc-lib-avx2
BuildRequires : glibc-libc32
BuildRequires : glibc-staticdev
BuildRequires : glog-dev
BuildRequires : glu
BuildRequires : glu-dev
BuildRequires : gmp
BuildRequires : gmp-dev
BuildRequires : gmp-staticdev
BuildRequires : gnutls
BuildRequires : gnutls-dev
BuildRequires : googletest
BuildRequires : googletest-dev
BuildRequires : graphite
BuildRequires : graphite-dev
BuildRequires : graphite-staticdev
BuildRequires : gsm-dev
BuildRequires : gsm-staticdev
BuildRequires : gstreamer-dev
BuildRequires : gtk+-data
BuildRequires : gtk+-lib
BuildRequires : gtk3-dev
BuildRequires : gtk3-lib
BuildRequires : h5py
BuildRequires : harfbuzz-dev
BuildRequires : harfbuzz-lib
BuildRequires : harfbuzz-staticdev
BuildRequires : hdf5
BuildRequires : hdf5-dev
BuildRequires : hdf5-lib
BuildRequires : hdf5-openmpi
BuildRequires : hdf5-staticdev
BuildRequires : icu4c-lib
BuildRequires : jack2
BuildRequires : jack2-dev
BuildRequires : json-c-staticdev
BuildRequires : jsoncpp
BuildRequires : jsoncpp-dev
BuildRequires : jsoncpp-lib
BuildRequires : jsoncpp-staticdev
BuildRequires : keyutils
BuildRequires : keyutils-dev
BuildRequires : krb5
BuildRequires : krb5-dev
BuildRequires : l-smash-dev
BuildRequires : l-smash-staticdev
BuildRequires : ladspa_sdk-dev
BuildRequires : ladspa_sdk-staticdev
BuildRequires : lcms2-dev
BuildRequires : lcms2-staticdev
BuildRequires : libICE-dev
BuildRequires : libSM-dev
BuildRequires : libX11-data
BuildRequires : libX11-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : libX11-lib
BuildRequires : libXScrnSaver
BuildRequires : libXScrnSaver-dev
BuildRequires : libXScrnSaver-lib
BuildRequires : libXau-dev
BuildRequires : libXau-lib
BuildRequires : libXcursor-dev
BuildRequires : libXcursor-lib
BuildRequires : libXdamage-dev
BuildRequires : libXdamage-lib
BuildRequires : libXdmcp-dev
BuildRequires : libXdmcp-lib
BuildRequires : libXext-dev
BuildRequires : libXext-lib
BuildRequires : libXfont2-dev
BuildRequires : libXft-dev
BuildRequires : libXft-lib
BuildRequires : libXi-dev
BuildRequires : libXi-lib
BuildRequires : libXrender-dev
BuildRequires : libXrender-lib
BuildRequires : libXtst-dev
BuildRequires : libXtst-lib
BuildRequires : libXxf86vm-dev
BuildRequires : libXxf86vm-dev32
BuildRequires : libXxf86vm-lib
BuildRequires : libaom-dev
BuildRequires : libaom-staticdev
BuildRequires : libarchive
BuildRequires : libarchive-dev
BuildRequires : libarchive-staticdev
BuildRequires : libass-dev
BuildRequires : libass-staticdev
BuildRequires : libatomic_ops-dev
BuildRequires : libatomic_ops-staticdev
BuildRequires : libbluray-dev
BuildRequires : libcap
BuildRequires : libcap-dev
BuildRequires : libcap-ng-dev
BuildRequires : libconfig-dev
BuildRequires : libconfig-staticdev
BuildRequires : libdrm
BuildRequires : libdrm-dev
BuildRequires : libdrm-lib
BuildRequires : libdrm-staticdev
BuildRequires : libedit
BuildRequires : libedit-dev
BuildRequires : libepoxy
BuildRequires : libepoxy-dev
BuildRequires : libepoxy-staticdev
BuildRequires : libfdk_aac-dev
BuildRequires : libfdk_aac-staticdev
BuildRequires : libffi
BuildRequires : libffi-dev
BuildRequires : libffi-staticdev
BuildRequires : libgcc1
BuildRequires : libgcrypt
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error
BuildRequires : libgpg-error-dev
BuildRequires : libgphoto2-dev
BuildRequires : libidn2
BuildRequires : libidn2-dev
BuildRequires : libidn2-staticdev
BuildRequires : libinput-data
BuildRequires : libinput-dev
BuildRequires : libinput-lib
BuildRequires : libinput-libexec
BuildRequires : libjpeg-turbo-dev
BuildRequires : libjpeg-turbo-staticdev
BuildRequires : libmp3lame-dev
BuildRequires : libmp3lame-staticdev
BuildRequires : libogg
BuildRequires : libogg-dev
BuildRequires : libogg-staticdev
BuildRequires : libpciaccess
BuildRequires : libpciaccess-dev
BuildRequires : libplacebo
BuildRequires : libplacebo-dev
BuildRequires : libplacebo-staticdev
BuildRequires : libpng
BuildRequires : libpng-dev
BuildRequires : libpng-lib
BuildRequires : libpng-staticdev
BuildRequires : librealsense-dev
BuildRequires : libsamplerate-dev
BuildRequires : libsamplerate-dev32
BuildRequires : libsamplerate-staticdev
BuildRequires : libsamplerate-staticdev32
BuildRequires : libsndfile-dev
BuildRequires : libsndfile-staticdev
BuildRequires : libsrt-dev
BuildRequires : libsrt-staticdev
BuildRequires : libstdc++
BuildRequires : libstdc++-dev
BuildRequires : libtasn1-dev
BuildRequires : libtasn1-staticdev
BuildRequires : libtheora-dev
BuildRequires : libtheora-staticdev
BuildRequires : libudfread-dev
BuildRequires : libudfread-staticdev
BuildRequires : libunistring-dev
BuildRequires : libunistring-staticdev
BuildRequires : libunwind
BuildRequires : libunwind-dev
BuildRequires : libusb
BuildRequires : libusb-dev
BuildRequires : libva
BuildRequires : libva-dev
BuildRequires : libva-intel-driver
BuildRequires : libva-lib
BuildRequires : libvapoursynth
BuildRequires : libvapoursynth-dev
BuildRequires : libvapoursynth-staticdev
BuildRequires : libvdpau
BuildRequires : libvdpau-dev
BuildRequires : libvorbis
BuildRequires : libvorbis-dev
BuildRequires : libvorbis-staticdev
BuildRequires : libvpx-dev
BuildRequires : libvpx-staticdev
BuildRequires : libwebp
BuildRequires : libwebp-dev
BuildRequires : libwebp-staticdev
BuildRequires : libx264-dev
BuildRequires : libx264-staticdev
BuildRequires : libx265-dev
BuildRequires : libx265-staticdev
BuildRequires : libxcb-dev
BuildRequires : libxcb-lib
BuildRequires : libxkbcommon
BuildRequires : libxkbcommon-dev
BuildRequires : libxml2-dev
BuildRequires : libxml2-staticdev
BuildRequires : libxslt-bin
BuildRequires : libxslt-dev
BuildRequires : libxslt-staticdev
BuildRequires : libxvid-dev
BuildRequires : libxvid-staticdev
BuildRequires : libzimg-dev
BuildRequires : libzimg-staticdev
BuildRequires : llvm
BuildRequires : llvm-abi
BuildRequires : llvm-bin
BuildRequires : llvm-data
BuildRequires : llvm-dev
BuildRequires : llvm-lib
BuildRequires : llvm-libexec
BuildRequires : llvm-man
BuildRequires : llvm-staticdev
BuildRequires : lrzip-dev
BuildRequires : lrzip-staticdev
BuildRequires : lz4
BuildRequires : lz4-dev
BuildRequires : lz4-staticdev
BuildRequires : lzo
BuildRequires : lzo-dev
BuildRequires : lzo-staticdev
BuildRequires : md4c
BuildRequires : md4c-dev
BuildRequires : md4c-staticdev
BuildRequires : mediasdk-dev
BuildRequires : mesa
BuildRequires : mesa-demos
BuildRequires : mesa-dev
BuildRequires : mesa-lib
BuildRequires : mkl-dnn-dev
BuildRequires : mm-common-dev
BuildRequires : nasm
BuildRequires : nasm-bin
BuildRequires : ncurses-dev
BuildRequires : nettle
BuildRequires : nettle-dev
BuildRequires : nettle-staticdev
BuildRequires : ninja
BuildRequires : not-ffmpeg
BuildRequires : not-ffmpeg-dev
BuildRequires : numlockx
BuildRequires : numpy
BuildRequires : numpy-dev
BuildRequires : numpy-stl
BuildRequires : nv-codec-headers-dev
BuildRequires : ocl-icd-dev
BuildRequires : onemkl
BuildRequires : onemkl-dev
BuildRequires : onemkl-lib
BuildRequires : onnx
BuildRequires : openblas
BuildRequires : openblas-dev
BuildRequires : openblas-staticdev
BuildRequires : opencl-headers
BuildRequires : opencl-headers-data
BuildRequires : opencl-headers-dev
BuildRequires : opencv-dev
BuildRequires : openjdk11-dev
BuildRequires : openjdk13
BuildRequires : openjdk13-dev
BuildRequires : openjpeg
BuildRequires : openjpeg-dev
BuildRequires : openjpeg-staticdev
BuildRequires : openssl
BuildRequires : openssl-dev
BuildRequires : openssl-lib
BuildRequires : openssl-staticdev
BuildRequires : opus-dev
BuildRequires : opus-staticdev
BuildRequires : orc-dev
BuildRequires : orc-staticdev
BuildRequires : p11-kit
BuildRequires : p11-kit-dev
BuildRequires : pacrunner
BuildRequires : pacrunner-dev
BuildRequires : pango-lib
BuildRequires : pcre-dev
BuildRequires : pcre-staticdev
BuildRequires : pcre2-dev
BuildRequires : pcre2-staticdev
BuildRequires : perl
BuildRequires : perl(XML::Parser)
BuildRequires : perl-Config-General
BuildRequires : perl-Config-Tiny
BuildRequires : perl-Crypt-SSLeay
BuildRequires : perl-DBI
BuildRequires : perl-DateTime-TimeZone
BuildRequires : perl-Encode-Locale
BuildRequires : perl-Error
BuildRequires : perl-File-Listing
BuildRequires : perl-HTML-Parser
BuildRequires : perl-HTML-Tagset
BuildRequires : perl-HTTP-Cookies
BuildRequires : perl-HTTP-Date
BuildRequires : perl-HTTP-Message
BuildRequires : perl-HTTP-Negotiate
BuildRequires : perl-IO-HTML
BuildRequires : perl-LWP-MediaTypes
BuildRequires : perl-LWP-Protocol-https
BuildRequires : perl-Params-Validate
BuildRequires : perl-Test-Simple
BuildRequires : perl-Try-Tiny
BuildRequires : perl-URI
BuildRequires : perl-XML-NamespaceSupport
BuildRequires : perl-XML-Parser
BuildRequires : perl-libwww-perl
BuildRequires : perl-man
BuildRequires : pip
BuildRequires : pixman
BuildRequires : pixman-dev
BuildRequires : pixman-lib
BuildRequires : pixman-staticdev
BuildRequires : pkg-config
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(32expat)
BuildRequires : pkgconfig(32glib-2.0)
BuildRequires : pkgconfig(32ice)
BuildRequires : pkgconfig(32libsystemd)
BuildRequires : pkgconfig(32sm)
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(Qt5Concurrent)
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5DBus)
BuildRequires : pkgconfig(Qt5Designer)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Help)
BuildRequires : pkgconfig(Qt5Location)
BuildRequires : pkgconfig(Qt5Multimedia)
BuildRequires : pkgconfig(Qt5Network)
BuildRequires : pkgconfig(Qt5OpenGL)
BuildRequires : pkgconfig(Qt5Pdf)
BuildRequires : pkgconfig(Qt5PdfWidgets)
BuildRequires : pkgconfig(Qt5PrintSupport)
BuildRequires : pkgconfig(Qt5Qml)
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : pkgconfig(Qt5QuickControls2)
BuildRequires : pkgconfig(Qt5QuickTest)
BuildRequires : pkgconfig(Qt5QuickWidgets)
BuildRequires : pkgconfig(Qt5Script)
BuildRequires : pkgconfig(Qt5Sensors)
BuildRequires : pkgconfig(Qt5SerialPort)
BuildRequires : pkgconfig(Qt5Sql)
BuildRequires : pkgconfig(Qt5Svg)
BuildRequires : pkgconfig(Qt5Test)
BuildRequires : pkgconfig(Qt5WebChannel)
BuildRequires : pkgconfig(Qt5WebEngine)
BuildRequires : pkgconfig(Qt5WebEngineCore)
BuildRequires : pkgconfig(Qt5WebEngineWidgets)
BuildRequires : pkgconfig(Qt5WebSockets)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(Qt5X11Extras)
BuildRequires : pkgconfig(Qt5Xml)
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(alsa-topology)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(dri)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(expat)
BuildRequires : pkgconfig(gbm)
BuildRequires : pkgconfig(gdm)
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(glesv1_cm)
BuildRequires : pkgconfig(glesv2)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(glu)
BuildRequires : pkgconfig(gmock)
BuildRequires : pkgconfig(gmock_main)
BuildRequires : pkgconfig(gstreamer-video-1.0)
BuildRequires : pkgconfig(gtest)
BuildRequires : pkgconfig(gtest_main)
BuildRequires : pkgconfig(ibus-1.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libpulse-simple)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libunwind)
BuildRequires : pkgconfig(libunwind-coredump)
BuildRequires : pkgconfig(libunwind-generic)
BuildRequires : pkgconfig(libunwind-ptrace)
BuildRequires : pkgconfig(libunwind-setjmp)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : pkgconfig(osmesa)
BuildRequires : pkgconfig(samplerate)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(tesseract)
BuildRequires : pkgconfig(valgrind)
BuildRequires : pkgconfig(vulkan)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(wayland-cursor)
BuildRequires : pkgconfig(wayland-egl)
BuildRequires : pkgconfig(wayland-protocols)
BuildRequires : pkgconfig(wayland-scanner)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xatracker)
BuildRequires : pkgconfig(xcursor)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xinerama)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(xmu)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xpm)
BuildRequires : pkgconfig(xproto)
BuildRequires : pkgconfig(xrandr)
BuildRequires : pkgconfig(xscrnsaver)
BuildRequires : pkgconfig(xt)
BuildRequires : pkgconfig(zlib)
BuildRequires : pluggy
BuildRequires : procps-ng
BuildRequires : protobuf-dev
BuildRequires : pugixml-dev
BuildRequires : pulseaudio
BuildRequires : pulseaudio-dev
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-pkgconfig
BuildRequires : python3-core
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : qca-qt5
BuildRequires : qca-qt5-dev
BuildRequires : qt3d
BuildRequires : qt3d-dev
BuildRequires : qt5ct
BuildRequires : qtbase
BuildRequires : qtbase-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtbase-extras
BuildRequires : qtcanvas3d
BuildRequires : qtcharts
BuildRequires : qtcharts-dev
BuildRequires : qtconnectivity
BuildRequires : qtconnectivity-dev
BuildRequires : qtdatavis3d
BuildRequires : qtdatavis3d-dev
BuildRequires : qtdeclarative
BuildRequires : qtdeclarative-dev
BuildRequires : qtgamepad
BuildRequires : qtgamepad-dev
BuildRequires : qtgraphicaleffects
BuildRequires : qtimageformats
BuildRequires : qtlocation
BuildRequires : qtlocation-dev
BuildRequires : qtmqtt
BuildRequires : qtmqtt-dev
BuildRequires : qtmultimedia
BuildRequires : qtmultimedia-dev
BuildRequires : qtnetworkauth
BuildRequires : qtnetworkauth-dev
BuildRequires : qtquickcontrols
BuildRequires : qtquickcontrols2
BuildRequires : qtquickcontrols2-dev
BuildRequires : qtremoteobjects-dev
BuildRequires : qtscript
BuildRequires : qtscript-dev
BuildRequires : qtscript-extras
BuildRequires : qtscxml
BuildRequires : qtscxml-dev
BuildRequires : qtsensors
BuildRequires : qtsensors-dev
BuildRequires : qtserialbus
BuildRequires : qtserialbus-dev
BuildRequires : qtserialport
BuildRequires : qtserialport-dev
BuildRequires : qtspeech
BuildRequires : qtspeech-dev
BuildRequires : qtsvg
BuildRequires : qtsvg-dev
BuildRequires : qttools
BuildRequires : qttools-dev
BuildRequires : qttranslations
BuildRequires : qtvirtualkeyboard
BuildRequires : qtvirtualkeyboard-dev
BuildRequires : qtwayland
BuildRequires : qtwayland-dev
BuildRequires : qtwebchannel
BuildRequires : qtwebchannel-dev
BuildRequires : qtwebengine
BuildRequires : qtwebengine-dev
BuildRequires : qtwebsockets
BuildRequires : qtwebsockets-dev
BuildRequires : qtx11extras
BuildRequires : qtx11extras-dev
BuildRequires : qtxmlpatterns
BuildRequires : qtxmlpatterns-dev
BuildRequires : rtmpdump-dev
BuildRequires : rtmpdump-staticdev
BuildRequires : rubberband-dev
BuildRequires : rubberband-staticdev
BuildRequires : sed
BuildRequires : setxkbmap
BuildRequires : shaderc-dev
BuildRequires : shaderc-staticdev
BuildRequires : shared-mime-info
BuildRequires : six
BuildRequires : snappy-dev
BuildRequires : snappy-staticdev
BuildRequires : solid-dev
BuildRequires : sonnet-dev
BuildRequires : speex-dev
BuildRequires : speex-staticdev
BuildRequires : speexdsp-dev
BuildRequires : speexdsp-staticdev
BuildRequires : sqlite-autoconf
BuildRequires : sqlite-autoconf-dev
BuildRequires : sqlite-autoconf-staticdev
BuildRequires : syntax-highlighting
BuildRequires : syntax-highlighting-data
BuildRequires : syntax-highlighting-dev
BuildRequires : syntax-highlighting-lib
BuildRequires : systemd
BuildRequires : systemd-dev
BuildRequires : tensorflow
BuildRequires : tesseract
BuildRequires : tesseract-bin
BuildRequires : tesseract-data
BuildRequires : tesseract-dev
BuildRequires : texinfo
BuildRequires : tiff
BuildRequires : tiff-dev
BuildRequires : tiff-staticdev
BuildRequires : tox
BuildRequires : uchardet-dev
BuildRequires : uchardet-staticdev
BuildRequires : util-linux
BuildRequires : util-linux-dev
BuildRequires : util-linux-staticdev
BuildRequires : v4l-utils-dev
BuildRequires : valgrind
BuildRequires : valgrind-dev
BuildRequires : vamp-sdk-dev
BuildRequires : vamp-sdk-staticdev
BuildRequires : virtualenv
BuildRequires : wayland
BuildRequires : wayland-dev
BuildRequires : weston
BuildRequires : wmctrl
BuildRequires : xauth
BuildRequires : xcb-proto
BuildRequires : xcb-proto-dev
BuildRequires : xcb-util-cursor-dev
BuildRequires : xcb-util-dev
BuildRequires : xcb-util-image-dev
BuildRequires : xcb-util-keysyms-dev
BuildRequires : xcb-util-renderutil-dev
BuildRequires : xcb-util-wm-dev
BuildRequires : xcb-util-xrm-dev
BuildRequires : xclip
BuildRequires : xdg-dbus-proxy
BuildRequires : xdg-desktop-portal
BuildRequires : xdg-desktop-portal-dev
BuildRequires : xdg-desktop-portal-gtk
BuildRequires : xdg-desktop-portal-kde
BuildRequires : xdg-user-dirs
BuildRequires : xdg-user-dirs-gtk
BuildRequires : xdg-utils
BuildRequires : xdotool
BuildRequires : xdpyinfo
BuildRequires : xf86-input-libinput
BuildRequires : xf86-video-amdgpu
BuildRequires : xf86-video-ati
BuildRequires : xf86-video-fbdev
BuildRequires : xf86-video-nouveau
BuildRequires : xf86-video-qxl
BuildRequires : xf86-video-vboxvideo
BuildRequires : xf86-video-vesa
BuildRequires : xf86-video-vmware
BuildRequires : xfontsel
BuildRequires : xhost
BuildRequires : xinit
BuildRequires : xinput
BuildRequires : xkbcomp
BuildRequires : xkeyboard-config
BuildRequires : xkill
BuildRequires : xmodmap
BuildRequires : xorg-server
BuildRequires : xorg-server-dev
BuildRequires : xorgproto
BuildRequires : xorgproto-dev
BuildRequires : xprop
BuildRequires : xrandr
BuildRequires : xrdb
BuildRequires : xrdp
BuildRequires : xrestop
BuildRequires : xscreensaver
BuildRequires : xsel
BuildRequires : xset
BuildRequires : xsetroot
BuildRequires : xvfb-run
BuildRequires : xwd
BuildRequires : xwininfo
BuildRequires : xz
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : yaml-cpp
BuildRequires : yaml-cpp-dev
BuildRequires : zlib
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
BuildRequires : zstd-dev
BuildRequires : zstd-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
A demo of the Java wrapper for OpenCV with two examples:
1) feature detection and matching and
2) face detection.
The examples are coded in Scala and Java.
Anyone familiar with Java should be able to read the Scala examples.
Please feel free to contribute code examples in Scala or Java, or any JVM language.

%package bin
Summary: bin components for the opencv package.
Group: Binaries
Requires: opencv-data = %{version}-%{release}

%description bin
bin components for the opencv package.


%package data
Summary: data components for the opencv package.
Group: Data

%description data
data components for the opencv package.


%package dev
Summary: dev components for the opencv package.
Group: Development
Requires: opencv-bin = %{version}-%{release}
Requires: opencv-data = %{version}-%{release}
Provides: opencv-devel = %{version}-%{release}
Requires: opencv = %{version}-%{release}

%description dev
dev components for the opencv package.


%package python
Summary: python components for the opencv package.
Group: Default
Requires: opencv-python3 = %{version}-%{release}

%description python
python components for the opencv package.


%package python3
Summary: python3 components for the opencv package.
Group: Default
Requires: python3-core

%description python3
python3 components for the opencv package.


%package staticdev
Summary: staticdev components for the opencv package.
Group: Default
Requires: opencv-dev = %{version}-%{release}

%description staticdev
staticdev components for the opencv package.


%prep
%setup -q -n opencv
cd %{_builddir}
tar xf %{_sourcedir}/opencv_contrib-v4.5.2.tar.gz
cd %{_builddir}/opencv
mkdir -p opencv_contrib
cp -r %{_builddir}/opencv_contrib/* %{_builddir}/opencv/opencv_contrib

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1622801677
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
## altflags_pgo content
## pgo generate
export PGO_GEN="-fprofile-generate=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-arcs -ftest-coverage --coverage -fprofile-partial-training"
export CFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export FCFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export FFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export CXXFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -fvisibility-inlines-hidden -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export LDFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
## pgo use
## -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fPIC -Wl,-z,max-page-size=0x1000 -fvisibility=hidden -flto-partition=none
## gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common -funroll-loops
export PGO_USE="-fprofile-use=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-correction -fprofile-partial-training"
export CFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export FCFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export FFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export CXXFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export LDFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread $PGO_USE"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
export CCACHE_DISABLE=true
#
#export NVCC_PREPEND_FLAGS="-O3 -Xptxas -O3,-v -cudart=static -ccbin=/usr/bin/gcc-10 -Xcompiler -O3,-static,-march=native,-mtune=native,-flto=16,-fuse-linker-plugin,-ffat-lto-objects,-fasynchronous-unwind-tables -Xlinker -flto=16,-fuse-linker-plugin,-ffat-lto-objects,-march=native,-mtune=native,-static -Xarchive -flto=16,-fuse-linker-plugin,-march=native,-mtune=native,-static"
#-gencode;arch=compute_52,code=sm_52
#-DWITH_CUDA=ON -DWITH_NVCUVID=ON -DWITH_NVCUVENC=OFF -DBUILD_opencv_cudacodec=ON -DWITH_CUDNN=OFF -DOPENCV_DNN_CUDA=OFF -DENABLE_FAST_MATH=1 -DCUDA_FAST_MATH=1 -DWITH_CUBLAS=1 -DWITH_V4L=ON -DOPENCV_GENERATE_PKGCONFIG=ON -DOPENCV_PC_FILE_NAME=opencv4.pc
export VERBOSE=1
export V=1
#
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/dri:/usr/lib64/haswell:/usr/lib64:/usr/lib:/usr/share"
#
export LIBRARY_PATH="$LIBRARY_PATH:/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/dri:/usr/lib64/haswell:/usr/lib64:/usr/lib:/usr/share"
#
export PATH="$PATH:/usr/local/cuda/bin:/usr/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
#
export CPATH="$CPATH:/usr/local/cuda/include/"
#
## altflags_pgo end
if [ ! -f statuspgo ]; then
echo PGO Phase 1
export CFLAGS="${CFLAGS_GENERATE}"
export CXXFLAGS="${CXXFLAGS_GENERATE}"
export FFLAGS="${FFLAGS_GENERATE}"
export FCFLAGS="${FCFLAGS_GENERATE}"
export LDFLAGS="${LDFLAGS_GENERATE}"
%cmake .. -GNinja \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_C_COMPILER=/usr/bin/gcc \
-DCMAKE_CXX_COMPILER=/usr/bin/g++ \
-DCMAKE_AR=/usr/bin/gcc-ar \
-DCMAKE_NM=/usr/bin/gcc-nm \
-DCMAKE_RANLIB=/usr/bin/gcc-ranlib \
-DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 \
-DCMAKE_INSTALL_PREFIX=/usr \
-DCMAKE_JOB_POOL_COMPILE=full_jobs \
-DCMAKE_JOB_POOL_LINK=full_jobs \
-DCMAKE_JOB_POOLS=full_jobs=16 \
-DCMAKE_VERBOSE_MAKEFILE:BOOL:BOOL=ON \
-Dverbose:BOOL=ON \
-DVERBOSE:BOOL=ON \
-DVERBOSE=1 \
-DBUILD_opencv_python2:BOOL=OFF \
-DHAVE_opencv_python2:BOOL=OFF \
-DBUILD_opencv_python3:BOOL=ON \
-DHAVE_opencv_python3:BOOL=ON \
-DBUILD_opencv_java:BOOL=OFF \
-DCPU_BASELINE=AVX2 \
-DCPU_DISPATCH= \
-DCV_DISABLE_OPTIMIZATION:BOOL=OFF \
-DCV_ENABLE_INTRINSICS:BOOL=ON \
-DCV_TRACE:BOOL=OFF \
-DBUILD_DOCS:BOOL=OFF \
-DENABLE_CCACHE:BOOL=OFF \
-DENABLE_FAST_MATH:BOOL=OFF \
-DENABLE_PIC:BOOL=ON \
-DWITH_TBB:BOOL=ON \
-DMKL_WITH_TBB:BOOL=ON \
-DMKL_USE_SINGLE_DYNAMIC_LIBRARY:BOOL=OFF \
-DMKL_WITH_OPENMP:BOOL=OFF \
-DBUILD_TBB:BOOL=OFF \
-DOPENCV_DNN_CUDA:BOOL=ON \
-DOPENCV_DNN_OPENCL:BOOL=ON \
-DOPENCV_ENABLE_NONFREE:BOOL=ON \
-DOPENCV_GENERATE_PKGCONFIG:BOOL=ON \
-DOPENCV_PYTHON_INSTALL_PATH=/usr/lib/python3.9/site-packages \
-DPYTHON3_EXECUTABLE:FILEPATH=/usr/bin/python3 \
-DPython2_EXECUTABLE= \
-DPYTHON2_EXECUTABLE= \
-DPARALLEL_ENABLE_PLUGINS:BOOL=ON \
-DBUILD_PNG:BOOL=OFF \
-DBUILD_JAVA:BOOL=OFF \
-DWITH_1394:BOOL=OFF \
-DWITH_ADE:BOOL=ON \
-DWITH_CUDA:BOOL=ON \
-DWITH_NGRAPH:BOOL=OFF \
-DCUDAToolkit_ROOT=/usr/local/cuda \
-DCUDNN_INCLUDE_DIR=/usr/local/cuda/include \
-DCUDA_NVCC_FLAGS="-O3;-Xptxas;-O3,-v;-cudart=static;-Xcompiler;-O3,-march=native,-fuse-linker-plugin,-ffat-lto-objects,-fasynchronous-unwind-tables,-pthread,-static-libstdc++,-static-libgcc;-Xlinker;-O3,-march=native,-fuse-linker-plugin,-ffat-lto-objects,-fasynchronous-unwind-tables,-pthread,-static-libstdc++,-static-libgcc;-Xarchive;-O3,-march=native,-fuse-linker-plugin,-ffat-lto-objects,-fasynchronous-unwind-tables,-pthread,-static-libstdc++,-static-libgcc" \
-DCUDA_ARCH_BIN=5.2 \
-DCUDA_HOST_COMPILER=/usr/bin/gcc-10 \
-DCUDA_PROPAGATE_HOST_FLAGS:BOOL=OFF \
-DCUDA_VERBOSE_BUILD:BOOL=ON \
-DWITH_EIGEN:BOOL=ON \
-DWITH_FFMPEG:BOOL=ON \
-DWITH_FREETYPE:BOOL=ON \
-DWITH_GSTREAMER:BOOL=ON \
-DWITH_GTK:BOOL=OFF \
-DWITH_IMGCODEC_HDR:BOOL=ON \
-DWITH_IMGCODEC_PFM:BOOL=ON \
-DWITH_IMGCODEC_PXM:BOOL=ON \
-DWITH_IMGCODEC_SUNRASTER:BOOL=ON \
-DBUILD_IPP_IW:BOOL=OFF \
-DWITH_IPP:BOOL=ON \
-DIPPROOT=/aot/intel/oneapi/ipp/latest/ \
-DBUILD_WITH_DYNAMIC_IPP=OFF \
-DOPENCV_IPP_GAUSSIAN_BLUR:BOOL=ON \
-DWITH_ITT:BOOL=ON \
-DWITH_JASPER:BOOL=OFF \
-DWITH_JPEG:BOOL=ON \
-DWITH_LAPACK:BOOL=ON \
-DWITH_MFX:BOOL=OFF \
-DWITH_OPENCLAMDBLAS:BOOL=ON \
-DWITH_OPENCLAMDFFT:BOOL=ON \
-DWITH_OPENCL:BOOL=ON \
-DWITH_OPENCL_SVM:BOOL=ON \
-DWITH_OPENEXR:BOOL=OFF \
-DWITH_OPENGL:BOOL=ON \
-DOPENGL_egl_LIBRARY:FILEPATH=/usr/nvidia/lib64/libEGL.so \
-DOPENGL_gl_LIBRARY:FILEPATH=/usr/nvidia/lib64/libGL.so \
-DOPENGL_gles2_LIBRARY:FILEPATH=/usr/nvidia/lib64/libGLESv2.so \
-DOPENGL_gles3_LIBRARY:FILEPATH=/usr/nvidia/lib64/libGLESv2.so \
-DOPENGL_glu_LIBRARY:FILEPATH=/usr/lib64/libGLU.so \
-DOPENGL_glx_LIBRARY:FILEPATH=/usr/nvidia/lib64/libGLX.so \
-DOPENGL_opengl_LIBRARY:FILEPATH=/usr/nvidia/lib64/libOpenGL.so \
-DOpenGL_GL_PREFERENCE=GLVND \
-DWITH_OPENJPEG:BOOL=ON \
-DWITH_OPENMP:BOOL=OFF \
-DWITH_PNG:BOOL=ON \
-DBUILD_PROTOBUF:BOOL=ON \
-DWITH_PROTOBUF:BOOL=ON \
-DWITH_PTHREADS_PF:BOOL=ON \
-DWITH_QT:BOOL=ON \
-DWITH_TIFF:BOOL=ON \
-DWITH_V4L:BOOL=OFF \
-DWITH_VA:BOOL=ON \
-DWITH_VA_INTEL:BOOL=ON \
-DWITH_VTK:BOOL=ON \
-DWITH_GDAL:BOOL=OFF \
-DWITH_VULKAN:BOOL=ON \
-DWITH_WEBP:BOOL=ON \
-DOPENCV_EXTRA_MODULES_PATH=/builddir/build/BUILD/opencv/opencv_contrib/modules/ \
-DENABLE_COVERAGE:BOOL=OFF \
-DENABLE_BUILD_HARDENING:BOOL=OFF \
-DINSTALL_C_EXAMPLES:BOOL=OFF \
-DINSTALL_PYTHON_EXAMPLES:BOOL=OFF \
-DINSTALL_TESTS:BOOL=OFF \
-DBUILD_EXAMPLES:BOOL=OFF \
-DBUILD_PERF_TESTS:BOOL=ON \
-DBUILD_TESTS:BOOL=OFF \
-DBUILD_opencv_python_tests:BOOL=OFF \
-DBUILD_opencv_apps=ON \
-DOPENCV_CONFIG_INSTALL_PATH=/usr/lib64/cmake/opencv4
## make_macro content
ninja --verbose
## make_macro end

#ctest -j16 --verbose --progress --timeout 300 || :
exit 1
export OPENCV_TEST_DATA_PATH=/builddir/build/BUILD/opencv/opencv_extra/testdata
python modules/ts/misc/run.py clr-build/ --perf_force_samples=1
# bin/opencv_perf_core || :
# bin/opencv_perf_imgproc || :
# bin/opencv_perf_dnn || :
# bin/opencv_perf_stitching || :
# bin/opencv_perf_features2d || :
# bin/opencv_perf_superres || :
find . -type f,l -not -name '*.gcno' -not -name 'statuspgo*' -delete -print
echo USED > statuspgo
fi
if [ -f statuspgo ]; then
echo PGO Phase 2
export CFLAGS="${CFLAGS_USE}"
export CXXFLAGS="${CXXFLAGS_USE}"
export FFLAGS="${FFLAGS_USE}"
export FCFLAGS="${FCFLAGS_USE}"
export LDFLAGS="${LDFLAGS_USE}"
%cmake .. -GNinja \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_C_COMPILER=/usr/bin/gcc \
-DCMAKE_CXX_COMPILER=/usr/bin/g++ \
-DCMAKE_AR=/usr/bin/gcc-ar \
-DCMAKE_NM=/usr/bin/gcc-nm \
-DCMAKE_RANLIB=/usr/bin/gcc-ranlib \
-DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 \
-DCMAKE_INSTALL_PREFIX=/usr \
-DCMAKE_JOB_POOL_COMPILE=full_jobs \
-DCMAKE_JOB_POOL_LINK=full_jobs \
-DCMAKE_JOB_POOLS=full_jobs=16 \
-DCMAKE_VERBOSE_MAKEFILE:BOOL:BOOL=ON \
-Dverbose:BOOL=ON \
-DVERBOSE:BOOL=ON \
-DVERBOSE=1 \
-DBUILD_opencv_python2:BOOL=OFF \
-DHAVE_opencv_python2:BOOL=OFF \
-DBUILD_opencv_python3:BOOL=ON \
-DHAVE_opencv_python3:BOOL=ON \
-DBUILD_opencv_java:BOOL=OFF \
-DCPU_BASELINE=AVX2 \
-DCPU_DISPATCH= \
-DCV_DISABLE_OPTIMIZATION:BOOL=OFF \
-DCV_ENABLE_INTRINSICS:BOOL=ON \
-DCV_TRACE:BOOL=OFF \
-DBUILD_DOCS:BOOL=OFF \
-DENABLE_CCACHE:BOOL=OFF \
-DENABLE_FAST_MATH:BOOL=OFF \
-DENABLE_PIC:BOOL=ON \
-DWITH_TBB:BOOL=ON \
-DMKL_WITH_TBB:BOOL=ON \
-DMKL_USE_SINGLE_DYNAMIC_LIBRARY:BOOL=OFF \
-DMKL_WITH_OPENMP:BOOL=OFF \
-DBUILD_TBB:BOOL=OFF \
-DOPENCV_DNN_CUDA:BOOL=ON \
-DOPENCV_DNN_OPENCL:BOOL=ON \
-DOPENCV_ENABLE_NONFREE:BOOL=ON \
-DOPENCV_GENERATE_PKGCONFIG:BOOL=ON \
-DOPENCV_PYTHON_INSTALL_PATH=/usr/lib/python3.9/site-packages \
-DPYTHON3_EXECUTABLE:FILEPATH=/usr/bin/python3 \
-DPython2_EXECUTABLE= \
-DPYTHON2_EXECUTABLE= \
-DPARALLEL_ENABLE_PLUGINS:BOOL=ON \
-DBUILD_PNG:BOOL=OFF \
-DBUILD_JAVA:BOOL=OFF \
-DWITH_1394:BOOL=OFF \
-DWITH_ADE:BOOL=ON \
-DWITH_CUDA:BOOL=ON \
-DWITH_NGRAPH:BOOL=OFF \
-DCUDAToolkit_ROOT=/usr/local/cuda \
-DCUDNN_INCLUDE_DIR=/usr/local/cuda/include \
-DCUDA_NVCC_FLAGS="-O3;-Xptxas;-O3,-v;-cudart=static;-Xcompiler;-O3,-march=native,-fuse-linker-plugin,-ffat-lto-objects,-fasynchronous-unwind-tables,-pthread,-static-libstdc++,-static-libgcc;-Xlinker;-O3,-march=native,-fuse-linker-plugin,-ffat-lto-objects,-fasynchronous-unwind-tables,-pthread,-static-libstdc++,-static-libgcc;-Xarchive;-O3,-march=native,-fuse-linker-plugin,-ffat-lto-objects,-fasynchronous-unwind-tables,-pthread,-static-libstdc++,-static-libgcc" \
-DCUDA_ARCH_BIN=5.2 \
-DCUDA_HOST_COMPILER=/usr/bin/gcc-10 \
-DCUDA_PROPAGATE_HOST_FLAGS:BOOL=OFF \
-DCUDA_VERBOSE_BUILD:BOOL=ON \
-DWITH_EIGEN:BOOL=ON \
-DWITH_FFMPEG:BOOL=ON \
-DWITH_FREETYPE:BOOL=ON \
-DWITH_GSTREAMER:BOOL=ON \
-DWITH_GTK:BOOL=OFF \
-DWITH_IMGCODEC_HDR:BOOL=ON \
-DWITH_IMGCODEC_PFM:BOOL=ON \
-DWITH_IMGCODEC_PXM:BOOL=ON \
-DWITH_IMGCODEC_SUNRASTER:BOOL=ON \
-DBUILD_IPP_IW:BOOL=OFF \
-DWITH_IPP:BOOL=ON \
-DIPPROOT=/aot/intel/oneapi/ipp/latest/ \
-DBUILD_WITH_DYNAMIC_IPP=OFF \
-DOPENCV_IPP_GAUSSIAN_BLUR:BOOL=ON \
-DWITH_ITT:BOOL=ON \
-DWITH_JASPER:BOOL=OFF \
-DWITH_JPEG:BOOL=ON \
-DWITH_LAPACK:BOOL=ON \
-DWITH_MFX:BOOL=OFF \
-DWITH_OPENCLAMDBLAS:BOOL=ON \
-DWITH_OPENCLAMDFFT:BOOL=ON \
-DWITH_OPENCL:BOOL=ON \
-DWITH_OPENCL_SVM:BOOL=ON \
-DWITH_OPENEXR:BOOL=OFF \
-DWITH_OPENGL:BOOL=ON \
-DOPENGL_egl_LIBRARY:FILEPATH=/usr/nvidia/lib64/libEGL.so \
-DOPENGL_gl_LIBRARY:FILEPATH=/usr/nvidia/lib64/libGL.so \
-DOPENGL_gles2_LIBRARY:FILEPATH=/usr/nvidia/lib64/libGLESv2.so \
-DOPENGL_gles3_LIBRARY:FILEPATH=/usr/nvidia/lib64/libGLESv2.so \
-DOPENGL_glu_LIBRARY:FILEPATH=/usr/lib64/libGLU.so \
-DOPENGL_glx_LIBRARY:FILEPATH=/usr/nvidia/lib64/libGLX.so \
-DOPENGL_opengl_LIBRARY:FILEPATH=/usr/nvidia/lib64/libOpenGL.so \
-DOpenGL_GL_PREFERENCE=GLVND \
-DWITH_OPENJPEG:BOOL=ON \
-DWITH_OPENMP:BOOL=OFF \
-DWITH_PNG:BOOL=ON \
-DBUILD_PROTOBUF:BOOL=ON \
-DWITH_PROTOBUF:BOOL=ON \
-DWITH_PTHREADS_PF:BOOL=ON \
-DWITH_QT:BOOL=ON \
-DWITH_TIFF:BOOL=ON \
-DWITH_V4L:BOOL=OFF \
-DWITH_VA:BOOL=ON \
-DWITH_VA_INTEL:BOOL=ON \
-DWITH_VTK:BOOL=ON \
-DWITH_GDAL:BOOL=OFF \
-DWITH_VULKAN:BOOL=ON \
-DWITH_WEBP:BOOL=ON \
-DOPENCV_EXTRA_MODULES_PATH=/builddir/build/BUILD/opencv/opencv_contrib/modules/ \
-DENABLE_COVERAGE:BOOL=OFF \
-DENABLE_BUILD_HARDENING:BOOL=OFF \
-DINSTALL_C_EXAMPLES:BOOL=OFF \
-DINSTALL_PYTHON_EXAMPLES:BOOL=OFF \
-DINSTALL_TESTS:BOOL=OFF \
-DBUILD_EXAMPLES:BOOL=OFF \
-DBUILD_PERF_TESTS:BOOL=OFF \
-DBUILD_TESTS:BOOL=OFF \
-DBUILD_opencv_python_tests:BOOL=OFF \
-DBUILD_opencv_apps=ON \
-DOPENCV_CONFIG_INSTALL_PATH=/usr/lib64/cmake/opencv4
## make_macro content
ninja --verbose
## make_macro end
fi
popd

%install
export SOURCE_DATE_EPOCH=1622801677
rm -rf %{buildroot}
pushd clr-build
%ninja_install
popd
## install_append content
# A bad idea but this will allow things that use pkgconfig to use opencv4
# Probably remove at some point once software updates build detection for new upstream release
cp %{buildroot}/usr/lib64/pkgconfig/opencv4.pc %{buildroot}/usr/lib64/pkgconfig/opencv.pc || :
install -dm 0755 %{buildroot}/usr/lib64/haswell/ || :
cp --archive %{buildroot}/usr/lib64/lib*.so* %{buildroot}/usr/lib64/haswell/ || :
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/opencv_annotation
/usr/bin/opencv_interactive-calibration
/usr/bin/opencv_model_diagnostics
/usr/bin/opencv_version
/usr/bin/opencv_visualisation
/usr/bin/opencv_waldboost_detector
/usr/bin/setup_vars_opencv4.sh

%files data
%defattr(-,root,root,-)
/usr/share/licenses/opencv4/SoftFloat-COPYING.txt
/usr/share/licenses/opencv4/ade-LICENSE
/usr/share/licenses/opencv4/opencl-headers-LICENSE.txt
/usr/share/licenses/opencv4/protobuf-LICENSE
/usr/share/licenses/opencv4/protobuf-README.md
/usr/share/licenses/opencv4/quirc-LICENSE
/usr/share/opencv4/haarcascades/haarcascade_eye.xml
/usr/share/opencv4/haarcascades/haarcascade_eye_tree_eyeglasses.xml
/usr/share/opencv4/haarcascades/haarcascade_frontalcatface.xml
/usr/share/opencv4/haarcascades/haarcascade_frontalcatface_extended.xml
/usr/share/opencv4/haarcascades/haarcascade_frontalface_alt.xml
/usr/share/opencv4/haarcascades/haarcascade_frontalface_alt2.xml
/usr/share/opencv4/haarcascades/haarcascade_frontalface_alt_tree.xml
/usr/share/opencv4/haarcascades/haarcascade_frontalface_default.xml
/usr/share/opencv4/haarcascades/haarcascade_fullbody.xml
/usr/share/opencv4/haarcascades/haarcascade_lefteye_2splits.xml
/usr/share/opencv4/haarcascades/haarcascade_licence_plate_rus_16stages.xml
/usr/share/opencv4/haarcascades/haarcascade_lowerbody.xml
/usr/share/opencv4/haarcascades/haarcascade_profileface.xml
/usr/share/opencv4/haarcascades/haarcascade_righteye_2splits.xml
/usr/share/opencv4/haarcascades/haarcascade_russian_plate_number.xml
/usr/share/opencv4/haarcascades/haarcascade_smile.xml
/usr/share/opencv4/haarcascades/haarcascade_upperbody.xml
/usr/share/opencv4/lbpcascades/lbpcascade_frontalcatface.xml
/usr/share/opencv4/lbpcascades/lbpcascade_frontalface.xml
/usr/share/opencv4/lbpcascades/lbpcascade_frontalface_improved.xml
/usr/share/opencv4/lbpcascades/lbpcascade_profileface.xml
/usr/share/opencv4/lbpcascades/lbpcascade_silverware.xml
/usr/share/opencv4/quality/brisque_model_live.yml
/usr/share/opencv4/quality/brisque_range_live.yml
/usr/share/opencv4/valgrind.supp
/usr/share/opencv4/valgrind_3rdparty.supp

%files dev
%defattr(-,root,root,-)
/usr/include/opencv4/opencv2/alphamat.hpp
/usr/include/opencv4/opencv2/aruco.hpp
/usr/include/opencv4/opencv2/aruco/charuco.hpp
/usr/include/opencv4/opencv2/aruco/dictionary.hpp
/usr/include/opencv4/opencv2/barcode.hpp
/usr/include/opencv4/opencv2/bgsegm.hpp
/usr/include/opencv4/opencv2/bioinspired.hpp
/usr/include/opencv4/opencv2/bioinspired/bioinspired.hpp
/usr/include/opencv4/opencv2/bioinspired/retina.hpp
/usr/include/opencv4/opencv2/bioinspired/retinafasttonemapping.hpp
/usr/include/opencv4/opencv2/bioinspired/transientareassegmentationmodule.hpp
/usr/include/opencv4/opencv2/calib3d.hpp
/usr/include/opencv4/opencv2/calib3d/calib3d.hpp
/usr/include/opencv4/opencv2/calib3d/calib3d_c.h
/usr/include/opencv4/opencv2/ccalib.hpp
/usr/include/opencv4/opencv2/ccalib/multicalib.hpp
/usr/include/opencv4/opencv2/ccalib/omnidir.hpp
/usr/include/opencv4/opencv2/ccalib/randpattern.hpp
/usr/include/opencv4/opencv2/core.hpp
/usr/include/opencv4/opencv2/core/affine.hpp
/usr/include/opencv4/opencv2/core/async.hpp
/usr/include/opencv4/opencv2/core/base.hpp
/usr/include/opencv4/opencv2/core/bindings_utils.hpp
/usr/include/opencv4/opencv2/core/bufferpool.hpp
/usr/include/opencv4/opencv2/core/check.hpp
/usr/include/opencv4/opencv2/core/core.hpp
/usr/include/opencv4/opencv2/core/core_c.h
/usr/include/opencv4/opencv2/core/cuda.hpp
/usr/include/opencv4/opencv2/core/cuda.inl.hpp
/usr/include/opencv4/opencv2/core/cuda/block.hpp
/usr/include/opencv4/opencv2/core/cuda/border_interpolate.hpp
/usr/include/opencv4/opencv2/core/cuda/color.hpp
/usr/include/opencv4/opencv2/core/cuda/common.hpp
/usr/include/opencv4/opencv2/core/cuda/datamov_utils.hpp
/usr/include/opencv4/opencv2/core/cuda/detail/color_detail.hpp
/usr/include/opencv4/opencv2/core/cuda/detail/reduce.hpp
/usr/include/opencv4/opencv2/core/cuda/detail/reduce_key_val.hpp
/usr/include/opencv4/opencv2/core/cuda/detail/transform_detail.hpp
/usr/include/opencv4/opencv2/core/cuda/detail/type_traits_detail.hpp
/usr/include/opencv4/opencv2/core/cuda/detail/vec_distance_detail.hpp
/usr/include/opencv4/opencv2/core/cuda/dynamic_smem.hpp
/usr/include/opencv4/opencv2/core/cuda/emulation.hpp
/usr/include/opencv4/opencv2/core/cuda/filters.hpp
/usr/include/opencv4/opencv2/core/cuda/funcattrib.hpp
/usr/include/opencv4/opencv2/core/cuda/functional.hpp
/usr/include/opencv4/opencv2/core/cuda/limits.hpp
/usr/include/opencv4/opencv2/core/cuda/reduce.hpp
/usr/include/opencv4/opencv2/core/cuda/saturate_cast.hpp
/usr/include/opencv4/opencv2/core/cuda/scan.hpp
/usr/include/opencv4/opencv2/core/cuda/simd_functions.hpp
/usr/include/opencv4/opencv2/core/cuda/transform.hpp
/usr/include/opencv4/opencv2/core/cuda/type_traits.hpp
/usr/include/opencv4/opencv2/core/cuda/utility.hpp
/usr/include/opencv4/opencv2/core/cuda/vec_distance.hpp
/usr/include/opencv4/opencv2/core/cuda/vec_math.hpp
/usr/include/opencv4/opencv2/core/cuda/vec_traits.hpp
/usr/include/opencv4/opencv2/core/cuda/warp.hpp
/usr/include/opencv4/opencv2/core/cuda/warp_reduce.hpp
/usr/include/opencv4/opencv2/core/cuda/warp_shuffle.hpp
/usr/include/opencv4/opencv2/core/cuda_stream_accessor.hpp
/usr/include/opencv4/opencv2/core/cuda_types.hpp
/usr/include/opencv4/opencv2/core/cv_cpu_dispatch.h
/usr/include/opencv4/opencv2/core/cv_cpu_helper.h
/usr/include/opencv4/opencv2/core/cvdef.h
/usr/include/opencv4/opencv2/core/cvstd.hpp
/usr/include/opencv4/opencv2/core/cvstd.inl.hpp
/usr/include/opencv4/opencv2/core/cvstd_wrapper.hpp
/usr/include/opencv4/opencv2/core/detail/async_promise.hpp
/usr/include/opencv4/opencv2/core/detail/exception_ptr.hpp
/usr/include/opencv4/opencv2/core/directx.hpp
/usr/include/opencv4/opencv2/core/dualquaternion.hpp
/usr/include/opencv4/opencv2/core/dualquaternion.inl.hpp
/usr/include/opencv4/opencv2/core/eigen.hpp
/usr/include/opencv4/opencv2/core/fast_math.hpp
/usr/include/opencv4/opencv2/core/hal/hal.hpp
/usr/include/opencv4/opencv2/core/hal/interface.h
/usr/include/opencv4/opencv2/core/hal/intrin.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_avx.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_avx512.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_cpp.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_forward.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_msa.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_neon.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_rvv.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_rvv071.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_sse.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_sse_em.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_vsx.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_wasm.hpp
/usr/include/opencv4/opencv2/core/hal/msa_macros.h
/usr/include/opencv4/opencv2/core/hal/simd_utils.impl.hpp
/usr/include/opencv4/opencv2/core/mat.hpp
/usr/include/opencv4/opencv2/core/mat.inl.hpp
/usr/include/opencv4/opencv2/core/matx.hpp
/usr/include/opencv4/opencv2/core/neon_utils.hpp
/usr/include/opencv4/opencv2/core/ocl.hpp
/usr/include/opencv4/opencv2/core/ocl_genbase.hpp
/usr/include/opencv4/opencv2/core/opencl/ocl_defs.hpp
/usr/include/opencv4/opencv2/core/opencl/opencl_info.hpp
/usr/include/opencv4/opencv2/core/opencl/opencl_svm.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_clamdblas.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_clamdfft.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_core.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_core_wrappers.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_gl.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_gl_wrappers.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_clamdblas.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_clamdfft.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_core.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_core_wrappers.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_gl.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_gl_wrappers.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_svm_20.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_svm_definitions.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_svm_hsa_extension.hpp
/usr/include/opencv4/opencv2/core/opengl.hpp
/usr/include/opencv4/opencv2/core/operations.hpp
/usr/include/opencv4/opencv2/core/optim.hpp
/usr/include/opencv4/opencv2/core/ovx.hpp
/usr/include/opencv4/opencv2/core/parallel/backend/parallel_for.openmp.hpp
/usr/include/opencv4/opencv2/core/parallel/backend/parallel_for.tbb.hpp
/usr/include/opencv4/opencv2/core/parallel/parallel_backend.hpp
/usr/include/opencv4/opencv2/core/persistence.hpp
/usr/include/opencv4/opencv2/core/quaternion.hpp
/usr/include/opencv4/opencv2/core/quaternion.inl.hpp
/usr/include/opencv4/opencv2/core/saturate.hpp
/usr/include/opencv4/opencv2/core/simd_intrinsics.hpp
/usr/include/opencv4/opencv2/core/softfloat.hpp
/usr/include/opencv4/opencv2/core/sse_utils.hpp
/usr/include/opencv4/opencv2/core/traits.hpp
/usr/include/opencv4/opencv2/core/types.hpp
/usr/include/opencv4/opencv2/core/types_c.h
/usr/include/opencv4/opencv2/core/utility.hpp
/usr/include/opencv4/opencv2/core/utils/allocator_stats.hpp
/usr/include/opencv4/opencv2/core/utils/allocator_stats.impl.hpp
/usr/include/opencv4/opencv2/core/utils/filesystem.hpp
/usr/include/opencv4/opencv2/core/utils/instrumentation.hpp
/usr/include/opencv4/opencv2/core/utils/logger.defines.hpp
/usr/include/opencv4/opencv2/core/utils/logger.hpp
/usr/include/opencv4/opencv2/core/utils/logtag.hpp
/usr/include/opencv4/opencv2/core/utils/tls.hpp
/usr/include/opencv4/opencv2/core/utils/trace.hpp
/usr/include/opencv4/opencv2/core/va_intel.hpp
/usr/include/opencv4/opencv2/core/version.hpp
/usr/include/opencv4/opencv2/core/vsx_utils.hpp
/usr/include/opencv4/opencv2/core_detect.hpp
/usr/include/opencv4/opencv2/cudaarithm.hpp
/usr/include/opencv4/opencv2/cudabgsegm.hpp
/usr/include/opencv4/opencv2/cudacodec.hpp
/usr/include/opencv4/opencv2/cudafeatures2d.hpp
/usr/include/opencv4/opencv2/cudafilters.hpp
/usr/include/opencv4/opencv2/cudaimgproc.hpp
/usr/include/opencv4/opencv2/cudalegacy.hpp
/usr/include/opencv4/opencv2/cudalegacy/NCV.hpp
/usr/include/opencv4/opencv2/cudalegacy/NCVBroxOpticalFlow.hpp
/usr/include/opencv4/opencv2/cudalegacy/NCVHaarObjectDetection.hpp
/usr/include/opencv4/opencv2/cudalegacy/NCVPyramid.hpp
/usr/include/opencv4/opencv2/cudalegacy/NPP_staging.hpp
/usr/include/opencv4/opencv2/cudaobjdetect.hpp
/usr/include/opencv4/opencv2/cudaoptflow.hpp
/usr/include/opencv4/opencv2/cudastereo.hpp
/usr/include/opencv4/opencv2/cudawarping.hpp
/usr/include/opencv4/opencv2/cudev.hpp
/usr/include/opencv4/opencv2/cudev/block/block.hpp
/usr/include/opencv4/opencv2/cudev/block/detail/reduce.hpp
/usr/include/opencv4/opencv2/cudev/block/detail/reduce_key_val.hpp
/usr/include/opencv4/opencv2/cudev/block/dynamic_smem.hpp
/usr/include/opencv4/opencv2/cudev/block/reduce.hpp
/usr/include/opencv4/opencv2/cudev/block/scan.hpp
/usr/include/opencv4/opencv2/cudev/block/vec_distance.hpp
/usr/include/opencv4/opencv2/cudev/common.hpp
/usr/include/opencv4/opencv2/cudev/expr/binary_func.hpp
/usr/include/opencv4/opencv2/cudev/expr/binary_op.hpp
/usr/include/opencv4/opencv2/cudev/expr/color.hpp
/usr/include/opencv4/opencv2/cudev/expr/deriv.hpp
/usr/include/opencv4/opencv2/cudev/expr/expr.hpp
/usr/include/opencv4/opencv2/cudev/expr/per_element_func.hpp
/usr/include/opencv4/opencv2/cudev/expr/reduction.hpp
/usr/include/opencv4/opencv2/cudev/expr/unary_func.hpp
/usr/include/opencv4/opencv2/cudev/expr/unary_op.hpp
/usr/include/opencv4/opencv2/cudev/expr/warping.hpp
/usr/include/opencv4/opencv2/cudev/functional/color_cvt.hpp
/usr/include/opencv4/opencv2/cudev/functional/detail/color_cvt.hpp
/usr/include/opencv4/opencv2/cudev/functional/functional.hpp
/usr/include/opencv4/opencv2/cudev/functional/tuple_adapter.hpp
/usr/include/opencv4/opencv2/cudev/grid/copy.hpp
/usr/include/opencv4/opencv2/cudev/grid/detail/copy.hpp
/usr/include/opencv4/opencv2/cudev/grid/detail/histogram.hpp
/usr/include/opencv4/opencv2/cudev/grid/detail/integral.hpp
/usr/include/opencv4/opencv2/cudev/grid/detail/minmaxloc.hpp
/usr/include/opencv4/opencv2/cudev/grid/detail/pyr_down.hpp
/usr/include/opencv4/opencv2/cudev/grid/detail/pyr_up.hpp
/usr/include/opencv4/opencv2/cudev/grid/detail/reduce.hpp
/usr/include/opencv4/opencv2/cudev/grid/detail/reduce_to_column.hpp
/usr/include/opencv4/opencv2/cudev/grid/detail/reduce_to_row.hpp
/usr/include/opencv4/opencv2/cudev/grid/detail/split_merge.hpp
/usr/include/opencv4/opencv2/cudev/grid/detail/transform.hpp
/usr/include/opencv4/opencv2/cudev/grid/detail/transpose.hpp
/usr/include/opencv4/opencv2/cudev/grid/histogram.hpp
/usr/include/opencv4/opencv2/cudev/grid/integral.hpp
/usr/include/opencv4/opencv2/cudev/grid/pyramids.hpp
/usr/include/opencv4/opencv2/cudev/grid/reduce.hpp
/usr/include/opencv4/opencv2/cudev/grid/reduce_to_vec.hpp
/usr/include/opencv4/opencv2/cudev/grid/split_merge.hpp
/usr/include/opencv4/opencv2/cudev/grid/transform.hpp
/usr/include/opencv4/opencv2/cudev/grid/transpose.hpp
/usr/include/opencv4/opencv2/cudev/ptr2d/constant.hpp
/usr/include/opencv4/opencv2/cudev/ptr2d/deriv.hpp
/usr/include/opencv4/opencv2/cudev/ptr2d/detail/gpumat.hpp
/usr/include/opencv4/opencv2/cudev/ptr2d/extrapolation.hpp
/usr/include/opencv4/opencv2/cudev/ptr2d/glob.hpp
/usr/include/opencv4/opencv2/cudev/ptr2d/gpumat.hpp
/usr/include/opencv4/opencv2/cudev/ptr2d/interpolation.hpp
/usr/include/opencv4/opencv2/cudev/ptr2d/lut.hpp
/usr/include/opencv4/opencv2/cudev/ptr2d/mask.hpp
/usr/include/opencv4/opencv2/cudev/ptr2d/remap.hpp
/usr/include/opencv4/opencv2/cudev/ptr2d/resize.hpp
/usr/include/opencv4/opencv2/cudev/ptr2d/texture.hpp
/usr/include/opencv4/opencv2/cudev/ptr2d/traits.hpp
/usr/include/opencv4/opencv2/cudev/ptr2d/transform.hpp
/usr/include/opencv4/opencv2/cudev/ptr2d/warping.hpp
/usr/include/opencv4/opencv2/cudev/ptr2d/zip.hpp
/usr/include/opencv4/opencv2/cudev/util/atomic.hpp
/usr/include/opencv4/opencv2/cudev/util/detail/tuple.hpp
/usr/include/opencv4/opencv2/cudev/util/detail/type_traits.hpp
/usr/include/opencv4/opencv2/cudev/util/limits.hpp
/usr/include/opencv4/opencv2/cudev/util/saturate_cast.hpp
/usr/include/opencv4/opencv2/cudev/util/simd_functions.hpp
/usr/include/opencv4/opencv2/cudev/util/tuple.hpp
/usr/include/opencv4/opencv2/cudev/util/type_traits.hpp
/usr/include/opencv4/opencv2/cudev/util/vec_math.hpp
/usr/include/opencv4/opencv2/cudev/util/vec_traits.hpp
/usr/include/opencv4/opencv2/cudev/warp/detail/reduce.hpp
/usr/include/opencv4/opencv2/cudev/warp/detail/reduce_key_val.hpp
/usr/include/opencv4/opencv2/cudev/warp/reduce.hpp
/usr/include/opencv4/opencv2/cudev/warp/scan.hpp
/usr/include/opencv4/opencv2/cudev/warp/shuffle.hpp
/usr/include/opencv4/opencv2/cudev/warp/warp.hpp
/usr/include/opencv4/opencv2/cvconfig.h
/usr/include/opencv4/opencv2/cvv.hpp
/usr/include/opencv4/opencv2/cvv/call_meta_data.hpp
/usr/include/opencv4/opencv2/cvv/cvv.hpp
/usr/include/opencv4/opencv2/cvv/debug_mode.hpp
/usr/include/opencv4/opencv2/cvv/dmatch.hpp
/usr/include/opencv4/opencv2/cvv/filter.hpp
/usr/include/opencv4/opencv2/cvv/final_show.hpp
/usr/include/opencv4/opencv2/cvv/show_image.hpp
/usr/include/opencv4/opencv2/datasets/ar_hmdb.hpp
/usr/include/opencv4/opencv2/datasets/ar_sports.hpp
/usr/include/opencv4/opencv2/datasets/dataset.hpp
/usr/include/opencv4/opencv2/datasets/fr_adience.hpp
/usr/include/opencv4/opencv2/datasets/fr_lfw.hpp
/usr/include/opencv4/opencv2/datasets/gr_chalearn.hpp
/usr/include/opencv4/opencv2/datasets/gr_skig.hpp
/usr/include/opencv4/opencv2/datasets/hpe_humaneva.hpp
/usr/include/opencv4/opencv2/datasets/hpe_parse.hpp
/usr/include/opencv4/opencv2/datasets/ir_affine.hpp
/usr/include/opencv4/opencv2/datasets/ir_robot.hpp
/usr/include/opencv4/opencv2/datasets/is_bsds.hpp
/usr/include/opencv4/opencv2/datasets/is_weizmann.hpp
/usr/include/opencv4/opencv2/datasets/msm_epfl.hpp
/usr/include/opencv4/opencv2/datasets/msm_middlebury.hpp
/usr/include/opencv4/opencv2/datasets/or_imagenet.hpp
/usr/include/opencv4/opencv2/datasets/or_mnist.hpp
/usr/include/opencv4/opencv2/datasets/or_pascal.hpp
/usr/include/opencv4/opencv2/datasets/or_sun.hpp
/usr/include/opencv4/opencv2/datasets/pd_caltech.hpp
/usr/include/opencv4/opencv2/datasets/pd_inria.hpp
/usr/include/opencv4/opencv2/datasets/slam_kitti.hpp
/usr/include/opencv4/opencv2/datasets/slam_tumindoor.hpp
/usr/include/opencv4/opencv2/datasets/sr_bsds.hpp
/usr/include/opencv4/opencv2/datasets/sr_div2k.hpp
/usr/include/opencv4/opencv2/datasets/sr_general100.hpp
/usr/include/opencv4/opencv2/datasets/tr_chars.hpp
/usr/include/opencv4/opencv2/datasets/tr_icdar.hpp
/usr/include/opencv4/opencv2/datasets/tr_svt.hpp
/usr/include/opencv4/opencv2/datasets/track_alov.hpp
/usr/include/opencv4/opencv2/datasets/track_vot.hpp
/usr/include/opencv4/opencv2/datasets/util.hpp
/usr/include/opencv4/opencv2/dnn.hpp
/usr/include/opencv4/opencv2/dnn/all_layers.hpp
/usr/include/opencv4/opencv2/dnn/dict.hpp
/usr/include/opencv4/opencv2/dnn/dnn.hpp
/usr/include/opencv4/opencv2/dnn/dnn.inl.hpp
/usr/include/opencv4/opencv2/dnn/layer.details.hpp
/usr/include/opencv4/opencv2/dnn/layer.hpp
/usr/include/opencv4/opencv2/dnn/shape_utils.hpp
/usr/include/opencv4/opencv2/dnn/utils/inference_engine.hpp
/usr/include/opencv4/opencv2/dnn/version.hpp
/usr/include/opencv4/opencv2/dnn_superres.hpp
/usr/include/opencv4/opencv2/dpm.hpp
/usr/include/opencv4/opencv2/face.hpp
/usr/include/opencv4/opencv2/face/bif.hpp
/usr/include/opencv4/opencv2/face/face_alignment.hpp
/usr/include/opencv4/opencv2/face/facemark.hpp
/usr/include/opencv4/opencv2/face/facemarkAAM.hpp
/usr/include/opencv4/opencv2/face/facemarkLBF.hpp
/usr/include/opencv4/opencv2/face/facemark_train.hpp
/usr/include/opencv4/opencv2/face/facerec.hpp
/usr/include/opencv4/opencv2/face/mace.hpp
/usr/include/opencv4/opencv2/face/predict_collector.hpp
/usr/include/opencv4/opencv2/features2d.hpp
/usr/include/opencv4/opencv2/features2d/features2d.hpp
/usr/include/opencv4/opencv2/features2d/hal/interface.h
/usr/include/opencv4/opencv2/flann.hpp
/usr/include/opencv4/opencv2/flann/all_indices.h
/usr/include/opencv4/opencv2/flann/allocator.h
/usr/include/opencv4/opencv2/flann/any.h
/usr/include/opencv4/opencv2/flann/autotuned_index.h
/usr/include/opencv4/opencv2/flann/composite_index.h
/usr/include/opencv4/opencv2/flann/config.h
/usr/include/opencv4/opencv2/flann/defines.h
/usr/include/opencv4/opencv2/flann/dist.h
/usr/include/opencv4/opencv2/flann/dummy.h
/usr/include/opencv4/opencv2/flann/dynamic_bitset.h
/usr/include/opencv4/opencv2/flann/flann.hpp
/usr/include/opencv4/opencv2/flann/flann_base.hpp
/usr/include/opencv4/opencv2/flann/general.h
/usr/include/opencv4/opencv2/flann/ground_truth.h
/usr/include/opencv4/opencv2/flann/hdf5.h
/usr/include/opencv4/opencv2/flann/heap.h
/usr/include/opencv4/opencv2/flann/hierarchical_clustering_index.h
/usr/include/opencv4/opencv2/flann/index_testing.h
/usr/include/opencv4/opencv2/flann/kdtree_index.h
/usr/include/opencv4/opencv2/flann/kdtree_single_index.h
/usr/include/opencv4/opencv2/flann/kmeans_index.h
/usr/include/opencv4/opencv2/flann/linear_index.h
/usr/include/opencv4/opencv2/flann/logger.h
/usr/include/opencv4/opencv2/flann/lsh_index.h
/usr/include/opencv4/opencv2/flann/lsh_table.h
/usr/include/opencv4/opencv2/flann/matrix.h
/usr/include/opencv4/opencv2/flann/miniflann.hpp
/usr/include/opencv4/opencv2/flann/nn_index.h
/usr/include/opencv4/opencv2/flann/object_factory.h
/usr/include/opencv4/opencv2/flann/params.h
/usr/include/opencv4/opencv2/flann/random.h
/usr/include/opencv4/opencv2/flann/result_set.h
/usr/include/opencv4/opencv2/flann/sampling.h
/usr/include/opencv4/opencv2/flann/saving.h
/usr/include/opencv4/opencv2/flann/simplex_downhill.h
/usr/include/opencv4/opencv2/flann/timer.h
/usr/include/opencv4/opencv2/freetype.hpp
/usr/include/opencv4/opencv2/fuzzy.hpp
/usr/include/opencv4/opencv2/fuzzy/fuzzy_F0_math.hpp
/usr/include/opencv4/opencv2/fuzzy/fuzzy_F1_math.hpp
/usr/include/opencv4/opencv2/fuzzy/fuzzy_image.hpp
/usr/include/opencv4/opencv2/fuzzy/types.hpp
/usr/include/opencv4/opencv2/gapi.hpp
/usr/include/opencv4/opencv2/gapi/core.hpp
/usr/include/opencv4/opencv2/gapi/cpu/core.hpp
/usr/include/opencv4/opencv2/gapi/cpu/gcpukernel.hpp
/usr/include/opencv4/opencv2/gapi/cpu/imgproc.hpp
/usr/include/opencv4/opencv2/gapi/cpu/stereo.hpp
/usr/include/opencv4/opencv2/gapi/cpu/video.hpp
/usr/include/opencv4/opencv2/gapi/fluid/core.hpp
/usr/include/opencv4/opencv2/gapi/fluid/gfluidbuffer.hpp
/usr/include/opencv4/opencv2/gapi/fluid/gfluidkernel.hpp
/usr/include/opencv4/opencv2/gapi/fluid/imgproc.hpp
/usr/include/opencv4/opencv2/gapi/garg.hpp
/usr/include/opencv4/opencv2/gapi/garray.hpp
/usr/include/opencv4/opencv2/gapi/gasync_context.hpp
/usr/include/opencv4/opencv2/gapi/gcall.hpp
/usr/include/opencv4/opencv2/gapi/gcommon.hpp
/usr/include/opencv4/opencv2/gapi/gcompiled.hpp
/usr/include/opencv4/opencv2/gapi/gcompiled_async.hpp
/usr/include/opencv4/opencv2/gapi/gcompoundkernel.hpp
/usr/include/opencv4/opencv2/gapi/gcomputation.hpp
/usr/include/opencv4/opencv2/gapi/gcomputation_async.hpp
/usr/include/opencv4/opencv2/gapi/gframe.hpp
/usr/include/opencv4/opencv2/gapi/gkernel.hpp
/usr/include/opencv4/opencv2/gapi/gmat.hpp
/usr/include/opencv4/opencv2/gapi/gmetaarg.hpp
/usr/include/opencv4/opencv2/gapi/gopaque.hpp
/usr/include/opencv4/opencv2/gapi/gproto.hpp
/usr/include/opencv4/opencv2/gapi/gpu/core.hpp
/usr/include/opencv4/opencv2/gapi/gpu/ggpukernel.hpp
/usr/include/opencv4/opencv2/gapi/gpu/imgproc.hpp
/usr/include/opencv4/opencv2/gapi/gscalar.hpp
/usr/include/opencv4/opencv2/gapi/gstreaming.hpp
/usr/include/opencv4/opencv2/gapi/gtransform.hpp
/usr/include/opencv4/opencv2/gapi/gtype_traits.hpp
/usr/include/opencv4/opencv2/gapi/gtyped.hpp
/usr/include/opencv4/opencv2/gapi/imgproc.hpp
/usr/include/opencv4/opencv2/gapi/infer.hpp
/usr/include/opencv4/opencv2/gapi/infer/bindings_ie.hpp
/usr/include/opencv4/opencv2/gapi/infer/ie.hpp
/usr/include/opencv4/opencv2/gapi/infer/onnx.hpp
/usr/include/opencv4/opencv2/gapi/infer/parsers.hpp
/usr/include/opencv4/opencv2/gapi/media.hpp
/usr/include/opencv4/opencv2/gapi/ocl/core.hpp
/usr/include/opencv4/opencv2/gapi/ocl/goclkernel.hpp
/usr/include/opencv4/opencv2/gapi/ocl/imgproc.hpp
/usr/include/opencv4/opencv2/gapi/opencv_includes.hpp
/usr/include/opencv4/opencv2/gapi/operators.hpp
/usr/include/opencv4/opencv2/gapi/own/assert.hpp
/usr/include/opencv4/opencv2/gapi/own/convert.hpp
/usr/include/opencv4/opencv2/gapi/own/cvdefs.hpp
/usr/include/opencv4/opencv2/gapi/own/exports.hpp
/usr/include/opencv4/opencv2/gapi/own/mat.hpp
/usr/include/opencv4/opencv2/gapi/own/saturate.hpp
/usr/include/opencv4/opencv2/gapi/own/scalar.hpp
/usr/include/opencv4/opencv2/gapi/own/types.hpp
/usr/include/opencv4/opencv2/gapi/plaidml/core.hpp
/usr/include/opencv4/opencv2/gapi/plaidml/gplaidmlkernel.hpp
/usr/include/opencv4/opencv2/gapi/plaidml/plaidml.hpp
/usr/include/opencv4/opencv2/gapi/python/python.hpp
/usr/include/opencv4/opencv2/gapi/render.hpp
/usr/include/opencv4/opencv2/gapi/render/render.hpp
/usr/include/opencv4/opencv2/gapi/render/render_types.hpp
/usr/include/opencv4/opencv2/gapi/rmat.hpp
/usr/include/opencv4/opencv2/gapi/s11n.hpp
/usr/include/opencv4/opencv2/gapi/s11n/base.hpp
/usr/include/opencv4/opencv2/gapi/stereo.hpp
/usr/include/opencv4/opencv2/gapi/streaming/cap.hpp
/usr/include/opencv4/opencv2/gapi/streaming/desync.hpp
/usr/include/opencv4/opencv2/gapi/streaming/format.hpp
/usr/include/opencv4/opencv2/gapi/streaming/meta.hpp
/usr/include/opencv4/opencv2/gapi/streaming/source.hpp
/usr/include/opencv4/opencv2/gapi/streaming/sync.hpp
/usr/include/opencv4/opencv2/gapi/util/any.hpp
/usr/include/opencv4/opencv2/gapi/util/compiler_hints.hpp
/usr/include/opencv4/opencv2/gapi/util/copy_through_move.hpp
/usr/include/opencv4/opencv2/gapi/util/optional.hpp
/usr/include/opencv4/opencv2/gapi/util/throw.hpp
/usr/include/opencv4/opencv2/gapi/util/type_traits.hpp
/usr/include/opencv4/opencv2/gapi/util/util.hpp
/usr/include/opencv4/opencv2/gapi/util/variant.hpp
/usr/include/opencv4/opencv2/gapi/video.hpp
/usr/include/opencv4/opencv2/hdf.hpp
/usr/include/opencv4/opencv2/hdf/hdf5.hpp
/usr/include/opencv4/opencv2/hfs.hpp
/usr/include/opencv4/opencv2/highgui.hpp
/usr/include/opencv4/opencv2/highgui/highgui.hpp
/usr/include/opencv4/opencv2/highgui/highgui_c.h
/usr/include/opencv4/opencv2/img_hash.hpp
/usr/include/opencv4/opencv2/img_hash/average_hash.hpp
/usr/include/opencv4/opencv2/img_hash/block_mean_hash.hpp
/usr/include/opencv4/opencv2/img_hash/color_moment_hash.hpp
/usr/include/opencv4/opencv2/img_hash/img_hash_base.hpp
/usr/include/opencv4/opencv2/img_hash/marr_hildreth_hash.hpp
/usr/include/opencv4/opencv2/img_hash/phash.hpp
/usr/include/opencv4/opencv2/img_hash/radial_variance_hash.hpp
/usr/include/opencv4/opencv2/imgcodecs.hpp
/usr/include/opencv4/opencv2/imgcodecs/imgcodecs.hpp
/usr/include/opencv4/opencv2/imgcodecs/imgcodecs_c.h
/usr/include/opencv4/opencv2/imgcodecs/ios.h
/usr/include/opencv4/opencv2/imgcodecs/legacy/constants_c.h
/usr/include/opencv4/opencv2/imgcodecs/macosx.h
/usr/include/opencv4/opencv2/imgproc.hpp
/usr/include/opencv4/opencv2/imgproc/bindings.hpp
/usr/include/opencv4/opencv2/imgproc/detail/gcgraph.hpp
/usr/include/opencv4/opencv2/imgproc/hal/hal.hpp
/usr/include/opencv4/opencv2/imgproc/hal/interface.h
/usr/include/opencv4/opencv2/imgproc/imgproc.hpp
/usr/include/opencv4/opencv2/imgproc/imgproc_c.h
/usr/include/opencv4/opencv2/imgproc/segmentation.hpp
/usr/include/opencv4/opencv2/imgproc/types_c.h
/usr/include/opencv4/opencv2/intensity_transform.hpp
/usr/include/opencv4/opencv2/line_descriptor.hpp
/usr/include/opencv4/opencv2/line_descriptor/descriptor.hpp
/usr/include/opencv4/opencv2/mcc.hpp
/usr/include/opencv4/opencv2/mcc/ccm.hpp
/usr/include/opencv4/opencv2/mcc/checker_detector.hpp
/usr/include/opencv4/opencv2/mcc/checker_model.hpp
/usr/include/opencv4/opencv2/ml.hpp
/usr/include/opencv4/opencv2/ml/ml.hpp
/usr/include/opencv4/opencv2/ml/ml.inl.hpp
/usr/include/opencv4/opencv2/objdetect.hpp
/usr/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp
/usr/include/opencv4/opencv2/objdetect/objdetect.hpp
/usr/include/opencv4/opencv2/opencv.hpp
/usr/include/opencv4/opencv2/opencv_modules.hpp
/usr/include/opencv4/opencv2/optflow.hpp
/usr/include/opencv4/opencv2/optflow/motempl.hpp
/usr/include/opencv4/opencv2/optflow/pcaflow.hpp
/usr/include/opencv4/opencv2/optflow/rlofflow.hpp
/usr/include/opencv4/opencv2/optflow/sparse_matching_gpc.hpp
/usr/include/opencv4/opencv2/phase_unwrapping.hpp
/usr/include/opencv4/opencv2/phase_unwrapping/histogramphaseunwrapping.hpp
/usr/include/opencv4/opencv2/phase_unwrapping/phase_unwrapping.hpp
/usr/include/opencv4/opencv2/photo.hpp
/usr/include/opencv4/opencv2/photo/cuda.hpp
/usr/include/opencv4/opencv2/photo/legacy/constants_c.h
/usr/include/opencv4/opencv2/photo/photo.hpp
/usr/include/opencv4/opencv2/plot.hpp
/usr/include/opencv4/opencv2/quality.hpp
/usr/include/opencv4/opencv2/quality/quality_utils.hpp
/usr/include/opencv4/opencv2/quality/qualitybase.hpp
/usr/include/opencv4/opencv2/quality/qualitybrisque.hpp
/usr/include/opencv4/opencv2/quality/qualitygmsd.hpp
/usr/include/opencv4/opencv2/quality/qualitymse.hpp
/usr/include/opencv4/opencv2/quality/qualitypsnr.hpp
/usr/include/opencv4/opencv2/quality/qualityssim.hpp
/usr/include/opencv4/opencv2/rapid.hpp
/usr/include/opencv4/opencv2/reg/map.hpp
/usr/include/opencv4/opencv2/reg/mapaffine.hpp
/usr/include/opencv4/opencv2/reg/mapper.hpp
/usr/include/opencv4/opencv2/reg/mappergradaffine.hpp
/usr/include/opencv4/opencv2/reg/mappergradeuclid.hpp
/usr/include/opencv4/opencv2/reg/mappergradproj.hpp
/usr/include/opencv4/opencv2/reg/mappergradshift.hpp
/usr/include/opencv4/opencv2/reg/mappergradsimilar.hpp
/usr/include/opencv4/opencv2/reg/mapperpyramid.hpp
/usr/include/opencv4/opencv2/reg/mapprojec.hpp
/usr/include/opencv4/opencv2/reg/mapshift.hpp
/usr/include/opencv4/opencv2/rgbd.hpp
/usr/include/opencv4/opencv2/rgbd/colored_kinfu.hpp
/usr/include/opencv4/opencv2/rgbd/depth.hpp
/usr/include/opencv4/opencv2/rgbd/detail/pose_graph.hpp
/usr/include/opencv4/opencv2/rgbd/dynafu.hpp
/usr/include/opencv4/opencv2/rgbd/intrinsics.hpp
/usr/include/opencv4/opencv2/rgbd/kinfu.hpp
/usr/include/opencv4/opencv2/rgbd/large_kinfu.hpp
/usr/include/opencv4/opencv2/rgbd/linemod.hpp
/usr/include/opencv4/opencv2/rgbd/volume.hpp
/usr/include/opencv4/opencv2/saliency.hpp
/usr/include/opencv4/opencv2/saliency/saliencyBaseClasses.hpp
/usr/include/opencv4/opencv2/saliency/saliencySpecializedClasses.hpp
/usr/include/opencv4/opencv2/sfm.hpp
/usr/include/opencv4/opencv2/sfm/conditioning.hpp
/usr/include/opencv4/opencv2/sfm/fundamental.hpp
/usr/include/opencv4/opencv2/sfm/io.hpp
/usr/include/opencv4/opencv2/sfm/numeric.hpp
/usr/include/opencv4/opencv2/sfm/projection.hpp
/usr/include/opencv4/opencv2/sfm/reconstruct.hpp
/usr/include/opencv4/opencv2/sfm/robust.hpp
/usr/include/opencv4/opencv2/sfm/simple_pipeline.hpp
/usr/include/opencv4/opencv2/sfm/triangulation.hpp
/usr/include/opencv4/opencv2/shape.hpp
/usr/include/opencv4/opencv2/shape/emdL1.hpp
/usr/include/opencv4/opencv2/shape/hist_cost.hpp
/usr/include/opencv4/opencv2/shape/shape.hpp
/usr/include/opencv4/opencv2/shape/shape_distance.hpp
/usr/include/opencv4/opencv2/shape/shape_transformer.hpp
/usr/include/opencv4/opencv2/stereo.hpp
/usr/include/opencv4/opencv2/stereo/descriptor.hpp
/usr/include/opencv4/opencv2/stereo/quasi_dense_stereo.hpp
/usr/include/opencv4/opencv2/stereo/stereo.hpp
/usr/include/opencv4/opencv2/stitching.hpp
/usr/include/opencv4/opencv2/stitching/detail/autocalib.hpp
/usr/include/opencv4/opencv2/stitching/detail/blenders.hpp
/usr/include/opencv4/opencv2/stitching/detail/camera.hpp
/usr/include/opencv4/opencv2/stitching/detail/exposure_compensate.hpp
/usr/include/opencv4/opencv2/stitching/detail/matchers.hpp
/usr/include/opencv4/opencv2/stitching/detail/motion_estimators.hpp
/usr/include/opencv4/opencv2/stitching/detail/seam_finders.hpp
/usr/include/opencv4/opencv2/stitching/detail/timelapsers.hpp
/usr/include/opencv4/opencv2/stitching/detail/util.hpp
/usr/include/opencv4/opencv2/stitching/detail/util_inl.hpp
/usr/include/opencv4/opencv2/stitching/detail/warpers.hpp
/usr/include/opencv4/opencv2/stitching/detail/warpers_inl.hpp
/usr/include/opencv4/opencv2/stitching/warpers.hpp
/usr/include/opencv4/opencv2/structured_light.hpp
/usr/include/opencv4/opencv2/structured_light/graycodepattern.hpp
/usr/include/opencv4/opencv2/structured_light/sinusoidalpattern.hpp
/usr/include/opencv4/opencv2/structured_light/structured_light.hpp
/usr/include/opencv4/opencv2/superres.hpp
/usr/include/opencv4/opencv2/superres/optical_flow.hpp
/usr/include/opencv4/opencv2/surface_matching.hpp
/usr/include/opencv4/opencv2/surface_matching/icp.hpp
/usr/include/opencv4/opencv2/surface_matching/pose_3d.hpp
/usr/include/opencv4/opencv2/surface_matching/ppf_helpers.hpp
/usr/include/opencv4/opencv2/surface_matching/ppf_match_3d.hpp
/usr/include/opencv4/opencv2/surface_matching/t_hash_int.hpp
/usr/include/opencv4/opencv2/text.hpp
/usr/include/opencv4/opencv2/text/erfilter.hpp
/usr/include/opencv4/opencv2/text/ocr.hpp
/usr/include/opencv4/opencv2/text/swt_text_detection.hpp
/usr/include/opencv4/opencv2/text/textDetector.hpp
/usr/include/opencv4/opencv2/tracking.hpp
/usr/include/opencv4/opencv2/tracking/feature.hpp
/usr/include/opencv4/opencv2/tracking/kalman_filters.hpp
/usr/include/opencv4/opencv2/tracking/onlineBoosting.hpp
/usr/include/opencv4/opencv2/tracking/tldDataset.hpp
/usr/include/opencv4/opencv2/tracking/tracking.hpp
/usr/include/opencv4/opencv2/tracking/tracking_by_matching.hpp
/usr/include/opencv4/opencv2/tracking/tracking_internals.hpp
/usr/include/opencv4/opencv2/tracking/tracking_legacy.hpp
/usr/include/opencv4/opencv2/video.hpp
/usr/include/opencv4/opencv2/video/background_segm.hpp
/usr/include/opencv4/opencv2/video/detail/tracking.detail.hpp
/usr/include/opencv4/opencv2/video/legacy/constants_c.h
/usr/include/opencv4/opencv2/video/tracking.hpp
/usr/include/opencv4/opencv2/video/video.hpp
/usr/include/opencv4/opencv2/videoio.hpp
/usr/include/opencv4/opencv2/videoio/cap_ios.h
/usr/include/opencv4/opencv2/videoio/legacy/constants_c.h
/usr/include/opencv4/opencv2/videoio/registry.hpp
/usr/include/opencv4/opencv2/videoio/videoio.hpp
/usr/include/opencv4/opencv2/videoio/videoio_c.h
/usr/include/opencv4/opencv2/videostab.hpp
/usr/include/opencv4/opencv2/videostab/deblurring.hpp
/usr/include/opencv4/opencv2/videostab/fast_marching.hpp
/usr/include/opencv4/opencv2/videostab/fast_marching_inl.hpp
/usr/include/opencv4/opencv2/videostab/frame_source.hpp
/usr/include/opencv4/opencv2/videostab/global_motion.hpp
/usr/include/opencv4/opencv2/videostab/inpainting.hpp
/usr/include/opencv4/opencv2/videostab/log.hpp
/usr/include/opencv4/opencv2/videostab/motion_core.hpp
/usr/include/opencv4/opencv2/videostab/motion_stabilizing.hpp
/usr/include/opencv4/opencv2/videostab/optical_flow.hpp
/usr/include/opencv4/opencv2/videostab/outlier_rejection.hpp
/usr/include/opencv4/opencv2/videostab/ring_buffer.hpp
/usr/include/opencv4/opencv2/videostab/stabilizer.hpp
/usr/include/opencv4/opencv2/videostab/wobble_suppression.hpp
/usr/include/opencv4/opencv2/viz.hpp
/usr/include/opencv4/opencv2/viz/types.hpp
/usr/include/opencv4/opencv2/viz/viz3d.hpp
/usr/include/opencv4/opencv2/viz/vizcore.hpp
/usr/include/opencv4/opencv2/viz/widget_accessor.hpp
/usr/include/opencv4/opencv2/viz/widgets.hpp
/usr/include/opencv4/opencv2/wechat_qrcode.hpp
/usr/include/opencv4/opencv2/xfeatures2d.hpp
/usr/include/opencv4/opencv2/xfeatures2d/cuda.hpp
/usr/include/opencv4/opencv2/xfeatures2d/nonfree.hpp
/usr/include/opencv4/opencv2/ximgproc.hpp
/usr/include/opencv4/opencv2/ximgproc/brightedges.hpp
/usr/include/opencv4/opencv2/ximgproc/color_match.hpp
/usr/include/opencv4/opencv2/ximgproc/deriche_filter.hpp
/usr/include/opencv4/opencv2/ximgproc/disparity_filter.hpp
/usr/include/opencv4/opencv2/ximgproc/edge_drawing.hpp
/usr/include/opencv4/opencv2/ximgproc/edge_filter.hpp
/usr/include/opencv4/opencv2/ximgproc/edgeboxes.hpp
/usr/include/opencv4/opencv2/ximgproc/edgepreserving_filter.hpp
/usr/include/opencv4/opencv2/ximgproc/estimated_covariance.hpp
/usr/include/opencv4/opencv2/ximgproc/fast_hough_transform.hpp
/usr/include/opencv4/opencv2/ximgproc/fast_line_detector.hpp
/usr/include/opencv4/opencv2/ximgproc/fourier_descriptors.hpp
/usr/include/opencv4/opencv2/ximgproc/lsc.hpp
/usr/include/opencv4/opencv2/ximgproc/paillou_filter.hpp
/usr/include/opencv4/opencv2/ximgproc/peilin.hpp
/usr/include/opencv4/opencv2/ximgproc/ridgefilter.hpp
/usr/include/opencv4/opencv2/ximgproc/run_length_morphology.hpp
/usr/include/opencv4/opencv2/ximgproc/seeds.hpp
/usr/include/opencv4/opencv2/ximgproc/segmentation.hpp
/usr/include/opencv4/opencv2/ximgproc/slic.hpp
/usr/include/opencv4/opencv2/ximgproc/sparse_match_interpolator.hpp
/usr/include/opencv4/opencv2/ximgproc/structured_edge_detection.hpp
/usr/include/opencv4/opencv2/ximgproc/weighted_median_filter.hpp
/usr/include/opencv4/opencv2/xobjdetect.hpp
/usr/include/opencv4/opencv2/xphoto.hpp
/usr/include/opencv4/opencv2/xphoto/bm3d_image_denoising.hpp
/usr/include/opencv4/opencv2/xphoto/dct_image_denoising.hpp
/usr/include/opencv4/opencv2/xphoto/inpainting.hpp
/usr/include/opencv4/opencv2/xphoto/oilpainting.hpp
/usr/include/opencv4/opencv2/xphoto/tonemap.hpp
/usr/include/opencv4/opencv2/xphoto/white_balance.hpp
/usr/lib64/cmake/opencv4/OpenCVConfig-version.cmake
/usr/lib64/cmake/opencv4/OpenCVConfig.cmake
/usr/lib64/cmake/opencv4/OpenCVModules-release.cmake
/usr/lib64/cmake/opencv4/OpenCVModules.cmake
/usr/lib64/pkgconfig/opencv.pc
/usr/lib64/pkgconfig/opencv4.pc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libopencv_alphamat.a
/usr/lib64/libopencv_aruco.a
/usr/lib64/libopencv_barcode.a
/usr/lib64/libopencv_bgsegm.a
/usr/lib64/libopencv_bioinspired.a
/usr/lib64/libopencv_calib3d.a
/usr/lib64/libopencv_ccalib.a
/usr/lib64/libopencv_core.a
/usr/lib64/libopencv_cudaarithm.a
/usr/lib64/libopencv_cudabgsegm.a
/usr/lib64/libopencv_cudacodec.a
/usr/lib64/libopencv_cudafeatures2d.a
/usr/lib64/libopencv_cudafilters.a
/usr/lib64/libopencv_cudaimgproc.a
/usr/lib64/libopencv_cudalegacy.a
/usr/lib64/libopencv_cudaobjdetect.a
/usr/lib64/libopencv_cudaoptflow.a
/usr/lib64/libopencv_cudastereo.a
/usr/lib64/libopencv_cudawarping.a
/usr/lib64/libopencv_cudev.a
/usr/lib64/libopencv_cvv.a
/usr/lib64/libopencv_datasets.a
/usr/lib64/libopencv_dnn.a
/usr/lib64/libopencv_dnn_objdetect.a
/usr/lib64/libopencv_dnn_superres.a
/usr/lib64/libopencv_dpm.a
/usr/lib64/libopencv_face.a
/usr/lib64/libopencv_features2d.a
/usr/lib64/libopencv_flann.a
/usr/lib64/libopencv_freetype.a
/usr/lib64/libopencv_fuzzy.a
/usr/lib64/libopencv_gapi.a
/usr/lib64/libopencv_hdf.a
/usr/lib64/libopencv_hfs.a
/usr/lib64/libopencv_highgui.a
/usr/lib64/libopencv_img_hash.a
/usr/lib64/libopencv_imgcodecs.a
/usr/lib64/libopencv_imgproc.a
/usr/lib64/libopencv_intensity_transform.a
/usr/lib64/libopencv_line_descriptor.a
/usr/lib64/libopencv_mcc.a
/usr/lib64/libopencv_ml.a
/usr/lib64/libopencv_objdetect.a
/usr/lib64/libopencv_optflow.a
/usr/lib64/libopencv_phase_unwrapping.a
/usr/lib64/libopencv_photo.a
/usr/lib64/libopencv_plot.a
/usr/lib64/libopencv_quality.a
/usr/lib64/libopencv_rapid.a
/usr/lib64/libopencv_reg.a
/usr/lib64/libopencv_rgbd.a
/usr/lib64/libopencv_saliency.a
/usr/lib64/libopencv_sfm.a
/usr/lib64/libopencv_shape.a
/usr/lib64/libopencv_stereo.a
/usr/lib64/libopencv_stitching.a
/usr/lib64/libopencv_structured_light.a
/usr/lib64/libopencv_superres.a
/usr/lib64/libopencv_surface_matching.a
/usr/lib64/libopencv_text.a
/usr/lib64/libopencv_tracking.a
/usr/lib64/libopencv_video.a
/usr/lib64/libopencv_videoio.a
/usr/lib64/libopencv_videostab.a
/usr/lib64/libopencv_viz.a
/usr/lib64/libopencv_wechat_qrcode.a
/usr/lib64/libopencv_xfeatures2d.a
/usr/lib64/libopencv_ximgproc.a
/usr/lib64/libopencv_xobjdetect.a
/usr/lib64/libopencv_xphoto.a
/usr/lib64/opencv4/3rdparty/libade.a
/usr/lib64/opencv4/3rdparty/libcorrespondence.a
/usr/lib64/opencv4/3rdparty/liblibprotobuf.a
/usr/lib64/opencv4/3rdparty/libmultiview.a
/usr/lib64/opencv4/3rdparty/libnumeric.a
/usr/lib64/opencv4/3rdparty/libquirc.a
